CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150546_InitialClienteModel') THEN
    CREATE TABLE personas (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        nombre character varying(100) NOT NULL,
        genero character varying(20) NOT NULL,
        edad integer NOT NULL,
        identificacion character varying(20) NOT NULL,
        direccion character varying(255) NOT NULL,
        telefono character varying(20) NOT NULL,
        CONSTRAINT "PK_personas" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150546_InitialClienteModel') THEN
    CREATE TABLE clientes (
        id bigint NOT NULL,
        contrasena character varying(255) NOT NULL,
        estado boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_clientes" PRIMARY KEY (id),
        CONSTRAINT "FK_clientes_personas_id" FOREIGN KEY (id) REFERENCES personas (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150546_InitialClienteModel') THEN
    CREATE UNIQUE INDEX "IX_personas_identificacion" ON personas (identificacion);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150546_InitialClienteModel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914150546_InitialClienteModel', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152029_RenameClienteIdColumn') THEN
    ALTER TABLE clientes DROP CONSTRAINT "FK_clientes_personas_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152029_RenameClienteIdColumn') THEN
    ALTER TABLE clientes RENAME COLUMN id TO cliente_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152029_RenameClienteIdColumn') THEN
    ALTER TABLE clientes ADD CONSTRAINT "FK_clientes_personas_cliente_id" FOREIGN KEY (cliente_id) REFERENCES personas (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152029_RenameClienteIdColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914152029_RenameClienteIdColumn', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152639_AddDataIntegrityCheckConstraints') THEN
    ALTER TABLE personas ALTER COLUMN edad TYPE smallint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152639_AddDataIntegrityCheckConstraints') THEN
    ALTER TABLE personas ADD CONSTRAINT "CK_personas_edad" CHECK (edad >= 0 AND edad <= 120);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152639_AddDataIntegrityCheckConstraints') THEN
    ALTER TABLE personas ADD CONSTRAINT "CK_personas_identificacion" CHECK (length(trim(identificacion)) >= 3);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152639_AddDataIntegrityCheckConstraints') THEN
    ALTER TABLE personas ADD CONSTRAINT "CK_personas_nombre" CHECK (length(trim(nombre)) >= 2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152639_AddDataIntegrityCheckConstraints') THEN
    ALTER TABLE clientes ADD CONSTRAINT "CK_clientes_contrasena" CHECK (length(trim(contrasena)) >= 4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152639_AddDataIntegrityCheckConstraints') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914152639_AddDataIntegrityCheckConstraints', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914161328_RenamePersonaIdColumn') THEN
    ALTER TABLE personas RENAME COLUMN id TO persona_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914161328_RenamePersonaIdColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914161328_RenamePersonaIdColumn', '9.0.4');
    END IF;
END $EF$;
COMMIT;

