
-- ==========================================================
-- CUENTAS Y MOVIMIENTOS
-- ==========================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150554_InitialCuentaMovimientoModel') THEN
    CREATE TABLE cuentas (
        numero_cuenta character varying(20) NOT NULL,
        tipo_cuenta character varying(20) NOT NULL,
        saldo_inicial numeric(18,2) NOT NULL,
        estado boolean NOT NULL DEFAULT TRUE,
        cliente_id bigint NOT NULL,
        CONSTRAINT "PK_cuentas" PRIMARY KEY (numero_cuenta)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150554_InitialCuentaMovimientoModel') THEN
    CREATE TABLE movimientos (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        fecha timestamp with time zone NOT NULL,
        tipo_movimiento character varying(50) NOT NULL,
        valor numeric(18,2) NOT NULL,
        saldo numeric(18,2) NOT NULL,
        numero_cuenta character varying(20) NOT NULL,
        CONSTRAINT "PK_movimientos" PRIMARY KEY (id),
        CONSTRAINT "FK_movimientos_cuentas_numero_cuenta" FOREIGN KEY (numero_cuenta) REFERENCES cuentas (numero_cuenta) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150554_InitialCuentaMovimientoModel') THEN
    CREATE INDEX "IX_cuentas_cliente_id" ON cuentas (cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150554_InitialCuentaMovimientoModel') THEN
    CREATE INDEX "IX_movimientos_fecha" ON movimientos (fecha);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150554_InitialCuentaMovimientoModel') THEN
    CREATE INDEX "IX_movimientos_numero_cuenta" ON movimientos (numero_cuenta);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914150554_InitialCuentaMovimientoModel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914150554_InitialCuentaMovimientoModel', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    ALTER TABLE movimientos ADD CONSTRAINT "CK_movimientos_saldo" CHECK (saldo >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    ALTER TABLE movimientos ADD CONSTRAINT "CK_movimientos_tipo" CHECK (tipo_movimiento IN ('Deposito', 'Retiro', 'Depósito'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    ALTER TABLE movimientos ADD CONSTRAINT "CK_movimientos_valor" CHECK (valor <> 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    ALTER TABLE cuentas ADD CONSTRAINT "CK_cuentas_numero_cuenta" CHECK (length(trim(numero_cuenta)) >= 4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    ALTER TABLE cuentas ADD CONSTRAINT "CK_cuentas_saldo_inicial" CHECK (saldo_inicial >= 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    ALTER TABLE cuentas ADD CONSTRAINT "CK_cuentas_tipo_cuenta" CHECK (tipo_cuenta IN ('Ahorros', 'Corriente'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914152704_AddBankingCheckConstraints') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914152704_AddBankingCheckConstraints', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914161407_RenameMovimientoIdColumn') THEN
    ALTER TABLE movimientos RENAME COLUMN id TO movimiento_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914161407_RenameMovimientoIdColumn') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914161407_RenameMovimientoIdColumn', '9.0.4');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    ALTER TABLE cuentas DROP CONSTRAINT "CK_cuentas_tipo_cuenta";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    ALTER TABLE cuentas DROP COLUMN tipo_cuenta;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    ALTER TABLE movimientos ALTER COLUMN numero_cuenta TYPE character varying(34);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    ALTER TABLE cuentas ALTER COLUMN numero_cuenta TYPE character varying(34);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    ALTER TABLE cuentas ADD tipo_cuenta_id smallint NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    CREATE TABLE tipos_cuenta (
        tipo_cuenta_id smallint GENERATED BY DEFAULT AS IDENTITY,
        codigo character varying(10) NOT NULL,
        nombre character varying(20) NOT NULL,
        CONSTRAINT "PK_tipos_cuenta" PRIMARY KEY (tipo_cuenta_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    INSERT INTO tipos_cuenta (tipo_cuenta_id, codigo, nombre)
    VALUES (1, 'AHORRO', 'Ahorros');
    INSERT INTO tipos_cuenta (tipo_cuenta_id, codigo, nombre)
    VALUES (2, 'CORRIENTE', 'Corriente');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    CREATE INDEX "IX_cuentas_tipo_cuenta_id" ON cuentas (tipo_cuenta_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    CREATE UNIQUE INDEX "IX_tipos_cuenta_codigo" ON tipos_cuenta (codigo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    CREATE UNIQUE INDEX "IX_tipos_cuenta_nombre" ON tipos_cuenta (nombre);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    ALTER TABLE cuentas ADD CONSTRAINT "FK_cuentas_tipos_cuenta_tipo_cuenta_id" FOREIGN KEY (tipo_cuenta_id) REFERENCES tipos_cuenta (tipo_cuenta_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    PERFORM setval(
        pg_get_serial_sequence('tipos_cuenta', 'tipo_cuenta_id'),
        GREATEST(
            (SELECT MAX(tipo_cuenta_id) FROM tipos_cuenta) + 1,
            nextval(pg_get_serial_sequence('tipos_cuenta', 'tipo_cuenta_id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914165701_AddTipoCuentaCatalogAndIbanAccountLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914165701_AddTipoCuentaCatalogAndIbanAccountLength', '9.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914224845_AddClienteProyeccionAndLedgerTrigger') THEN
    CREATE TABLE cliente_proyecciones (
        cliente_id bigint NOT NULL,
        nombre character varying(100) NOT NULL,
        identificacion character varying(20) NOT NULL,
        estado boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_cliente_proyecciones" PRIMARY KEY (cliente_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914224845_AddClienteProyeccionAndLedgerTrigger') THEN
    INSERT INTO cliente_proyecciones (cliente_id, estado, identificacion, nombre)
    VALUES (1, true, '1234567890', 'Jose Lema');
    INSERT INTO cliente_proyecciones (cliente_id, estado, identificacion, nombre)
    VALUES (2, true, '0975489650', 'Marianela Montalvo');
    INSERT INTO cliente_proyecciones (cliente_id, estado, identificacion, nombre)
    VALUES (3, true, '0988745870', 'Juan Osorio');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914224845_AddClienteProyeccionAndLedgerTrigger') THEN
    CREATE OR REPLACE FUNCTION fn_validar_saldo_ledger()
    RETURNS TRIGGER AS $func$
    DECLARE
        v_saldo_inicial NUMERIC(18,2);
        v_saldo_acumulado NUMERIC(18,2);
        v_saldo_anterior NUMERIC(18,2);
    BEGIN
        SELECT saldo_inicial INTO v_saldo_inicial
        FROM cuentas
        WHERE numero_cuenta = NEW.numero_cuenta
        FOR UPDATE;

        IF NOT FOUND THEN
            RETURN NEW;
        END IF;

        SELECT COALESCE(SUM(valor), 0.00) INTO v_saldo_acumulado
        FROM movimientos
        WHERE numero_cuenta = NEW.numero_cuenta;

        v_saldo_anterior := v_saldo_inicial + v_saldo_acumulado;

        -- Asignar el saldo exacto resultante secuencial acumulado
        -- Si el saldo resultante es negativo, PostgreSQL disparará automáticamente CK_movimientos_saldo
        NEW.saldo := v_saldo_anterior + NEW.valor;

        RETURN NEW;
    END;
    $func$ LANGUAGE plpgsql;

    DROP TRIGGER IF EXISTS trg_validar_saldo_ledger ON movimientos;
    CREATE TRIGGER trg_validar_saldo_ledger
    BEFORE INSERT ON movimientos
    FOR EACH ROW
    EXECUTE FUNCTION fn_validar_saldo_ledger();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260914224845_AddClienteProyeccionAndLedgerTrigger') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260914224845_AddClienteProyeccionAndLedgerTrigger', '9.0.4');
    END IF;
END $EF$;
COMMIT;


