// <auto-generated />
using System;
using CuentaMovimientoService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuentaMovimientoService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CuentaMovimientoDbContext))]
    partial class CuentaMovimientoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.ClienteProyeccion", b =>
                {
                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("ClienteId");

                    b.ToTable("cliente_proyecciones", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1L,
                            Estado = true,
                            Identificacion = "1234567890",
                            Nombre = "Jose Lema"
                        },
                        new
                        {
                            ClienteId = 2L,
                            Estado = true,
                            Identificacion = "0975489650",
                            Nombre = "Marianela Montalvo"
                        },
                        new
                        {
                            ClienteId = 3L,
                            Estado = true,
                            Identificacion = "0988745870",
                            Nombre = "Juan Osorio"
                        });
                });

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.Cuenta", b =>
                {
                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("numero_cuenta");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<short>("TipoCuentaId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_cuenta_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("NumeroCuenta");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoCuentaId");

                    b.ToTable("cuentas", null, t =>
                        {
                            t.HasCheckConstraint("CK_cuentas_numero_cuenta", "length(trim(numero_cuenta)) >= 4");

                            t.HasCheckConstraint("CK_cuentas_saldo_inicial", "saldo_inicial >= 0");
                        });
                });

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.Movimiento", b =>
                {
                    b.Property<long>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("movimiento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MovimientoId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("numero_cuenta");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("MovimientoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("NumeroCuenta");

                    b.ToTable("movimientos", null, t =>
                        {
                            t.HasCheckConstraint("CK_movimientos_saldo", "saldo >= 0");

                            t.HasCheckConstraint("CK_movimientos_tipo", "tipo_movimiento IN ('Deposito', 'Retiro', 'Depósito')");

                            t.HasCheckConstraint("CK_movimientos_valor", "valor <> 0");
                        });
                });

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.TipoCuentaItem", b =>
                {
                    b.Property<short>("TipoCuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_cuenta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("TipoCuentaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nombre");

                    b.HasKey("TipoCuentaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_cuenta", (string)null);

                    b.HasData(
                        new
                        {
                            TipoCuentaId = (short)1,
                            Codigo = "AHORRO",
                            Nombre = "Ahorros"
                        },
                        new
                        {
                            TipoCuentaId = (short)2,
                            Codigo = "CORRIENTE",
                            Nombre = "Corriente"
                        });
                });

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("CuentaMovimientoService.Domain.Entities.TipoCuentaItem", "TipoCuentaItem")
                        .WithMany()
                        .HasForeignKey("TipoCuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCuentaItem");
                });

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("CuentaMovimientoService.Domain.Entities.Cuenta", "Cuenta")
                        .WithMany("Movimientos")
                        .HasForeignKey("NumeroCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CuentaMovimientoService.Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
